services:
  ##############################
  # app(Apache + PHP)
  ##############################
    test-app:
        container_name: test-app
        build: ./docker/app
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www
        depends_on:
            - test-app-mysql
    test-app-mysql:
        container_name: test-app-mysql
        build: ./docker/mysql
        ports:
            - "33306:3306"
        environment:
            MYSQL_DATABASE: test-app
            MYSQL_USER: appuser
            MYSQL_PASSWORD: appuser
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
